"""Atualizacao 2026_07_17

Revision ID: 152bd428932c
Revises: 37a57ff7eeae
Create Date: 2026-07-17 18:27:45.856352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152bd428932c'
down_revision = '37a57ff7eeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('item_venda_produto_id_fkey'), type_='foreignkey')
        batch_op.drop_column('produto_id')

    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_venda_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'item_venda', ['item_venda_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_venda_id')

    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('item_venda_produto_id_fkey'), 'produto', ['produto_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
