"""Inicializacao

Revision ID: 26465fa9a21b
Revises: 
Create Date: 2026-06-25 15:03:21.341492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26465fa9a21b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('granja',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('identificacao', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('role',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('sexo',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('nome', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cargo',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('role_permissao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permissao_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_financas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('status_lote_frango',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_despesa',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_movimentacao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_produto',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_racao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_receita',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_unidade_medida',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('sigla', sa.String(length=8), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('tipo_venda',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('sexo_id', sa.BigInteger(), nullable=True),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('salario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sexo_id'], ['sexo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('endereco',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('cliente_id', sa.BigInteger(), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('rua', sa.String(length=128), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro_logradouro', sa.String(length=128), nullable=False),
    sa.Column('cidade', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escolaridades',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_frango',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('status_lote_frango_id', sa.BigInteger(), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('identificacao', sa.String(length=32), nullable=False),
    sa.Column('quantidade_inicial', sa.Integer(), nullable=True),
    sa.Column('data_alojamento', sa.Date(), nullable=False),
    sa.Column('fornecedor', sa.String(length=128), nullable=True),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_lote_frango_id'], ['status_lote_frango.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacao')
    )
    op.create_table('lote_racao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('tipo_racao_id', sa.BigInteger(), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('fornecedor', sa.String(length=100), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('quilos', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_racao_id'], ['tipo_racao.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('tipo_produto_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_unidade_medida_id', sa.BigInteger(), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_produto_id'], ['tipo_produto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_unidade_medida_id'], ['tipo_unidade_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_granja',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('granja_id', sa.BigInteger(), nullable=True),
    sa.Column('cargo_id', sa.BigInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=True),
    sa.Column('status_financas_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_venda_id', sa.BigInteger(), nullable=False),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_financas_id'], ['status_financas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_venda_id'], ['tipo_venda.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo_lote_diaria',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('lote_frango_id', sa.BigInteger(), nullable=False),
    sa.Column('lote_racao_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('quilos', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['lote_frango_id'], ['lote_frango.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_racao_id'], ['lote_racao.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesa',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('tipo_despesa_id', sa.BigInteger(), nullable=False),
    sa.Column('status_financas_id', sa.BigInteger(), nullable=False),
    sa.Column('lote_frango_id', sa.BigInteger(), nullable=True),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_frango_id'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_financas_id'], ['status_financas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_despesa_id'], ['tipo_despesa.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade_atual', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id')
    )
    op.create_table('item_venda',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('venda_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortalidade',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('lote_frango_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quantidade_mortes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lote_frango_id'], ['lote_frango.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('lote_frango_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('data_producao', sa.Date(), nullable=False),
    sa.Column('observacao', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['lote_frango_id'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('tipo_receita_id', sa.BigInteger(), nullable=False),
    sa.Column('status_financas_id', sa.BigInteger(), nullable=False),
    sa.Column('venda_id', sa.BigInteger(), nullable=True),
    sa.Column('granja_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_financas_id'], ['status_financas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_receita_id'], ['tipo_receita.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacao_estoque',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('producao_id', sa.BigInteger(), nullable=True),
    sa.Column('item_venda_id', sa.BigInteger(), nullable=True),
    sa.Column('tipo_movimentacao_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacao', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['item_venda_id'], ['item_venda.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producao_id'], ['producao.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_movimentacao_id'], ['tipo_movimentacao.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao_estoque')
    op.drop_table('receita')
    op.drop_table('producao')
    op.drop_table('mortalidade')
    op.drop_table('item_venda')
    op.drop_table('estoque')
    op.drop_table('despesa')
    op.drop_table('consumo_lote_diaria')
    op.drop_table('venda')
    op.drop_table('usuario_granja')
    op.drop_table('produto')
    op.drop_table('lote_racao')
    op.drop_table('lote_frango')
    op.drop_table('escolaridades')
    op.drop_table('endereco')
    op.drop_table('usuario')
    op.drop_table('tipo_venda')
    op.drop_table('tipo_unidade_medida')
    op.drop_table('tipo_receita')
    op.drop_table('tipo_racao')
    op.drop_table('tipo_produto')
    op.drop_table('tipo_movimentacao')
    op.drop_table('tipo_despesa')
    op.drop_table('status_lote_frango')
    op.drop_table('status_financas')
    op.drop_table('role_permissao')
    op.drop_table('cargo')
    op.drop_table('sexo')
    op.drop_table('role')
    op.drop_table('permissao')
    op.drop_table('granja')
    op.drop_table('cliente')
    # ### end Alembic commands ###
