"""Atualizacao 2026_06_26 1.0

Revision ID: 2bfa21de0f33
Revises: 9616bb15b081
Create Date: 2026-06-26 08:02:14.016989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfa21de0f33'
down_revision = '9616bb15b081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('sexo_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('salario',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('salario',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('sexo_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
