"""Atualizacao 2026_07_15

Revision ID: 37a57ff7eeae
Revises: d8f44147288f
Create Date: 2026-07-15 09:33:23.522737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a57ff7eeae'
down_revision = 'd8f44147288f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)

    with op.batch_alter_table('consumo_lote_diaria', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('consumo_lote_diaria_lote_racao_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lote_racao', ['lote_racao_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumo_lote_diaria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consumo_lote_diaria_lote_racao_id_fkey'), 'lote_racao', ['lote_racao_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=18),
               nullable=False)

    # ### end Alembic commands ###
