"""atualizacao 2026_07_09 1.1

Revision ID: 4db971989f1b
Revises: d137338ff07d
Create Date: 2026-07-09 21:06:24.182990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db971989f1b'
down_revision = 'd137338ff07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_associacao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuario_associacao_usuario_destino_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('usuario_associacao_usuario_origem_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_destino_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['usuario_origem_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_associacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuario_associacao_usuario_origem_id_fkey'), 'usuario', ['usuario_origem_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('usuario_associacao_usuario_destino_id_fkey'), 'usuario', ['usuario_destino_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
