"""atualizacao salario user

Revision ID: 50c732b86ada
Revises: b7e608e0049a
Create Date: 2026-07-07 08:36:15.381972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c732b86ada'
down_revision = 'b7e608e0049a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('salario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salario', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
