"""Atualizacao lote_racao 1.0

Revision ID: 67d78ae52ed8
Revises: 50c732b86ada
Create Date: 2026-07-08 08:42:10.934332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d78ae52ed8'
down_revision = '50c732b86ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_racao', schema=None) as batch_op:
        batch_op.drop_column('data_compra')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_racao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_compra', sa.DATE(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
