"""atualizacao 2.0

Revision ID: 6c6de06acbe2
Revises: 2bfa21de0f33
Create Date: 2026-06-28 10:39:35.943072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6de06acbe2'
down_revision = '2bfa21de0f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granja_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'granja', ['granja_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('lote_racao', schema=None) as batch_op:
        batch_op.drop_column('valor')

    with op.batch_alter_table('tipo_produto', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('tipo_racao', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_racao', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('tipo_produto', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('lote_racao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('granja_id')

    # ### end Alembic commands ###
