"""Atualizacao 2026_07_17 1.1

Revision ID: 8c060ea03131
Revises: 152bd428932c
Create Date: 2026-07-17 18:34:48.619089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c060ea03131'
down_revision = '152bd428932c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('item_venda_venda_id_fkey'), type_='foreignkey')
        batch_op.drop_column('venda_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venda_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('item_venda_venda_id_fkey'), 'venda', ['venda_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
