"""Atualizacao 1.5

Revision ID: 9616bb15b081
Revises: 26465fa9a21b
Create Date: 2026-06-25 15:10:43.981941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9616bb15b081'
down_revision = '26465fa9a21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('sexo_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('data_entrada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_entrada', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.alter_column('sexo_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
