"""Atualizacao 2026_07_17 1.2

Revision ID: 99e07f8562a7
Revises: 8c060ea03131
Create Date: 2026-07-17 18:40:25.049599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e07f8562a7'
down_revision = '8c060ea03131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venda_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('produto_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'venda', ['venda_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'produto', ['produto_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('venda_item_venda_id_fkey'), type_='foreignkey')
        batch_op.drop_column('item_venda_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_venda_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('venda_item_venda_id_fkey'), 'item_venda', ['item_venda_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('produto_id')
        batch_op.drop_column('venda_id')

    # ### end Alembic commands ###
