"""Atualizacao 2026_07_22

Revision ID: b681c50916a4
Revises: 99e07f8562a7
Create Date: 2026-07-21 20:47:53.469840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b681c50916a4'
down_revision = '99e07f8562a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.drop_column('valor_unitario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_unitario', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
