"""Atualizacao 2026_07_04 1.0

Revision ID: b7e608e0049a
Revises: 34264d5d2e73
Create Date: 2026-07-04 06:03:04.407529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e608e0049a'
down_revision = '34264d5d2e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_estoque', sa.Numeric(precision=15, scale=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('quantidade_estoque')

    # ### end Alembic commands ###
