"""Atualizacao 2026_07_31

Revision ID: c82141d8ad83
Revises: b681c50916a4
Create Date: 2026-07-31 16:42:15.769643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82141d8ad83'
down_revision = 'b681c50916a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=False))
        batch_op.drop_column('data_producao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_producao', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###
