"""atualizacao bd 2026_07_09

Revision ID: d137338ff07d
Revises: 67d78ae52ed8
Create Date: 2026-07-09 20:35:00.405867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd137338ff07d'
down_revision = '67d78ae52ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_associacao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('usuario_origem_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_destino_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_origem_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_associacao')
    # ### end Alembic commands ###
