"""atualizacao 3.1

Revision ID: d8f44147288f
Revises: 5e8b05440cc5
Create Date: 2026-07-11 15:07:52.712867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f44147288f'
down_revision = '5e8b05440cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_frango', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lote_frango_identificacao_key'), type_='unique')
        batch_op.create_unique_constraint('uq_lote_frango_granja_identificacao', ['granja_id', 'identificacao'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_frango', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lote_frango_granja_identificacao', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('lote_frango_identificacao_key'), ['identificacao'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
